---
title: "Data within VDAT files"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data within VDAT files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This vignette is a working draft. There will be lots of changes as `rvdat` gets fleshed out, so please check back often!

The most recent changes were made on 2024-07-08.


```r
library(rvdat)
```

## Data columns

The table below shows each receiver/VDAT type along with, in alphabetical order, each logged data type (attitude, battery, etc.) and their respective column names/data fields in bullets.


```
#> 0.0% - Converting File7.6% - Converting File9.2% - Converting File10.7% - Converting File12.2% - Converting File13.7% - Converting File15.3% - Converting File16.8% - Converting File18.3% - Converting File19.8% - Converting File21.4% - Converting File22.9% - Converting File24.4% - Converting File26.0% - Converting File27.5% - Converting File29.0% - Converting File30.5% - Converting File32.1% - Converting File33.6% - Converting File35.1% - Converting File36.6% - Converting File38.2% - Converting File39.7% - Converting File41.2% - Converting File42.7% - Converting File44.3% - Converting File45.8% - Converting File47.3% - Converting File48.9% - Converting File50.4% - Converting File51.9% - Converting File53.4% - Converting File55.0% - Converting File56.5% - Converting File58.0% - Converting File59.5% - Converting File61.1% - Converting File62.6% - Converting File64.1% - Converting File65.6% - Converting File67.2% - Converting File68.7% - Converting File70.2% - Converting File71.8% - Converting File73.3% - Converting File74.8% - Converting File76.3% - Converting File77.9% - Converting File79.4% - Converting File80.9% - Converting File82.4% - Converting File84.0% - Converting File85.5% - Converting File87.0% - Converting File88.5% - Converting File90.1% - Converting File91.6% - Converting File93.1% - Converting File94.7% - Converting File96.2% - Converting File97.7% - Converting File100.0% - Converting File                        
```





```
#>   receiver file_type n_data_types
#> 1  HR2-180      VDAT           26
#> 2    VR2AR       VRL           25
#> 3    VR2TX       VRL           25
#> 4     VR2W       VRL           27
#> 5  VR2W180       VRL           27
```






### HR2-180 VDAT, n = 26

#### ATTITUDE, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Tilt (deg)

:::

::::

#### BATTERY, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Battery Position
 - Battery Type
 - Battery Serial Number
 - Battery Voltage (V)
 - Battery Remaining (%)

:::

::::

#### CFG_CHANNEL, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Channel
 - Detection Type
 - Frequency (kHz)
 - Blanking (ms)
 - Map ID
 - Coding ID

:::

::::

#### CFG_STATION, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Station Name
 - Latitude (deg)
 - Longitude (deg)

:::

::::

#### CFG_STUDY, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Description

:::

::::

#### CFG_TRANSMITTER, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Transmission Type
 - Full ID
 - ID
 - Power Level
 - Min Delay (s)
 - Max Delay (s)

:::

::::

#### CLOCK_REF, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - External Time (UTC)
 - External Difference (s)
 - Source

:::

::::

#### CLOCK_SET, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - Prior Difference (s)
 - Source

:::

::::

#### DATA_ERROR, n = 5

:::: {style="display: flex;"}

::: {}

 - Type
 - Error
 - Page

:::

::: {}

 - Offset
 - Description

:::

::::

#### DATA_SOURCE_FILE, n = 5

:::: {style="display: flex;"}

::: {}

 - File Name
 - UUID
 - Type

:::

::: {}

 - Size
 - State

:::

::::

#### DEPTH, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Depth (m)

:::

::::

#### DEPTH_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Depth Min (m)
 - Depth Max (m)
 - Depth Mean (m)
 - Sample Count
 - Accumulation Period (s)

:::

::::

#### DET, n = 20

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID

:::

::: {}

 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### DET_FILTER, n = 3

:::: {style="display: flex;"}

::: {}

 - Filter Name
 - Details

:::

::: {}

 - Rejected Detections

:::

::::

#### DET_SENS, n = 25

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID
 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)

:::

::: {}

 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP
 - Transmitter Type
 - Sensor Function
 - Sensor Value
 - Sensor Unit
 - Sensor Precision

:::

::::

#### DIAG, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Temperature (deg C)
 - Noise Mean (mV)
 - Tilt (deg)
 - Depth (m)
 - PPM Pings
 - PPM Detections

:::

::::

#### DIAG_FAST, n = 10

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Ambient Temperature (deg C)
 - Noise (mV)
 - Tilt (deg)
 - Depth (m)

:::

::::

#### DIAG_HR2, n = 15

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Tilt (deg)
 - HR Noise (dB)

:::

::: {}

 - HR Accepted Detections
 - HR Rejected Detections
 - PPM Pings (D1)
 - PPM Detections (D1)
 - PPM Pings (D2)
 - PPM Detections (D2)
 - PPM Noise (dB)

:::

::::

#### EVENT, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Type

:::

::: {}

 - Subtype
 - Description
 - Values
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### EVENT_FAULT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Fault Importance
 - Fault Code
 - Fault Description

:::

::::

#### EVENT_INIT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - External Time Zone
 - Firmware Version

:::

::::

#### EVENT_OFFLOAD, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - External Time (UTC)

:::

::: {}

 - External Time Zone
 - HR Total Accepted Detections
 - PPM Total Accepted Detections
 - Memory Remaining (%)
 - Battery Remaining (%)
 - Original File

:::

::::

#### HEALTH_HR2, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Line Voltage (V)
 - Memory Remaining (%)
 - RTC Time

:::

::::

#### PING, n = 15

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Frequency (kHz)

:::

::: {}

 - Blanking (ms)
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### TEMP, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Ambient (deg C)
 - Internal (deg C)

:::

::::

#### TEMP_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Min (deg C)
 - Ambient Max (deg C)
 - Ambient Mean (deg C)
 - Sample Count
 - Accumulation Period (s)

:::

::::

### VR2AR VRL, n = 25

#### ATTITUDE, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Tilt (deg)

:::

::::

#### BATTERY, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Battery Position
 - Battery Type
 - Battery Serial Number
 - Battery Voltage (V)
 - Battery Remaining (%)

:::

::::

#### CFG_CHANNEL, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Channel
 - Detection Type
 - Frequency (kHz)
 - Blanking (ms)
 - Map ID
 - Coding ID

:::

::::

#### CFG_STATION, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Station Name
 - Latitude (deg)
 - Longitude (deg)

:::

::::

#### CFG_STUDY, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Description

:::

::::

#### CFG_TRANSMITTER, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Transmission Type
 - Full ID
 - ID
 - Power Level
 - Min Delay (s)
 - Max Delay (s)

:::

::::

#### CLOCK_REF, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - External Time (UTC)
 - External Difference (s)
 - Source

:::

::::

#### CLOCK_SET, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - Prior Difference (s)
 - Source

:::

::::

#### DATA_ERROR, n = 5

:::: {style="display: flex;"}

::: {}

 - Type
 - Error
 - Page

:::

::: {}

 - Offset
 - Description

:::

::::

#### DATA_SOURCE_FILE, n = 5

:::: {style="display: flex;"}

::: {}

 - File Name
 - UUID
 - Type

:::

::: {}

 - Size
 - State

:::

::::

#### DEPTH, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Depth (m)

:::

::::

#### DEPTH_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Depth Min (m)
 - Depth Max (m)
 - Depth Mean (m)
 - Sample Count
 - Accumulation Period (s)

:::

::::

#### DET, n = 20

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID

:::

::: {}

 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### DET_FILTER, n = 3

:::: {style="display: flex;"}

::: {}

 - Filter Name
 - Details

:::

::: {}

 - Rejected Detections

:::

::::

#### DET_SENS, n = 25

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID
 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)

:::

::: {}

 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP
 - Transmitter Type
 - Sensor Function
 - Sensor Value
 - Sensor Unit
 - Sensor Precision

:::

::::

#### DIAG, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Temperature (deg C)
 - Noise Mean (mV)
 - Tilt (deg)
 - Depth (m)
 - PPM Pings
 - PPM Detections

:::

::::

#### DIAG_FAST, n = 10

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Ambient Temperature (deg C)
 - Noise (mV)
 - Tilt (deg)
 - Depth (m)

:::

::::

#### EVENT, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Type

:::

::: {}

 - Subtype
 - Description
 - Values
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### EVENT_FAULT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Fault Importance
 - Fault Code
 - Fault Description

:::

::::

#### EVENT_INIT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - External Time Zone
 - Firmware Version

:::

::::

#### EVENT_OFFLOAD, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - External Time (UTC)

:::

::: {}

 - External Time Zone
 - HR Total Accepted Detections
 - PPM Total Accepted Detections
 - Memory Remaining (%)
 - Battery Remaining (%)
 - Original File

:::

::::

#### HEALTH_VR2AR, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Memory Remaining (%)
 - RTC Time

:::

::::

#### PING, n = 15

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Frequency (kHz)

:::

::: {}

 - Blanking (ms)
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### TEMP, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Ambient (deg C)
 - Internal (deg C)

:::

::::

#### TEMP_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Min (deg C)
 - Ambient Max (deg C)
 - Ambient Mean (deg C)
 - Sample Count
 - Accumulation Period (s)

:::

::::

### VR2TX VRL, n = 25

#### ATTITUDE, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Tilt (deg)

:::

::::

#### BATTERY, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Battery Position
 - Battery Type
 - Battery Serial Number
 - Battery Voltage (V)
 - Battery Remaining (%)

:::

::::

#### CFG_CHANNEL, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Channel
 - Detection Type
 - Frequency (kHz)
 - Blanking (ms)
 - Map ID
 - Coding ID

:::

::::

#### CFG_STATION, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Station Name
 - Latitude (deg)
 - Longitude (deg)

:::

::::

#### CFG_STUDY, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Description

:::

::::

#### CFG_TRANSMITTER, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Transmission Type
 - Full ID
 - ID
 - Power Level
 - Min Delay (s)
 - Max Delay (s)

:::

::::

#### CLOCK_REF, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - External Time (UTC)
 - External Difference (s)
 - Source

:::

::::

#### CLOCK_SET, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - Prior Difference (s)
 - Source

:::

::::

#### DATA_ERROR, n = 5

:::: {style="display: flex;"}

::: {}

 - Type
 - Error
 - Page

:::

::: {}

 - Offset
 - Description

:::

::::

#### DATA_SOURCE_FILE, n = 5

:::: {style="display: flex;"}

::: {}

 - File Name
 - UUID
 - Type

:::

::: {}

 - Size
 - State

:::

::::

#### DEPTH, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Depth (m)

:::

::::

#### DEPTH_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Depth Min (m)
 - Depth Max (m)
 - Depth Mean (m)
 - Sample Count
 - Accumulation Period (s)

:::

::::

#### DET, n = 20

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID

:::

::: {}

 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### DET_FILTER, n = 3

:::: {style="display: flex;"}

::: {}

 - Filter Name
 - Details

:::

::: {}

 - Rejected Detections

:::

::::

#### DET_SENS, n = 25

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID
 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)

:::

::: {}

 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP
 - Transmitter Type
 - Sensor Function
 - Sensor Value
 - Sensor Unit
 - Sensor Precision

:::

::::

#### DIAG, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Temperature (deg C)
 - Noise Mean (mV)
 - Tilt (deg)
 - Depth (m)
 - PPM Pings
 - PPM Detections

:::

::::

#### DIAG_FAST, n = 10

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Ambient Temperature (deg C)
 - Noise (mV)
 - Tilt (deg)
 - Depth (m)

:::

::::

#### EVENT, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Type

:::

::: {}

 - Subtype
 - Description
 - Values
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### EVENT_FAULT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Fault Importance
 - Fault Code
 - Fault Description

:::

::::

#### EVENT_INIT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - External Time Zone
 - Firmware Version

:::

::::

#### EVENT_OFFLOAD, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - External Time (UTC)

:::

::: {}

 - External Time Zone
 - HR Total Accepted Detections
 - PPM Total Accepted Detections
 - Memory Remaining (%)
 - Battery Remaining (%)
 - Original File

:::

::::

#### HEALTH_VR2TX, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Memory Remaining (%)
 - RTC Time

:::

::::

#### PING, n = 15

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Frequency (kHz)

:::

::: {}

 - Blanking (ms)
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### TEMP, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Ambient (deg C)
 - Internal (deg C)

:::

::::

#### TEMP_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Min (deg C)
 - Ambient Max (deg C)
 - Ambient Mean (deg C)
 - Sample Count
 - Accumulation Period (s)

:::

::::

### VR2W VRL, n = 27

#### ATTITUDE, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Tilt (deg)

:::

::::

#### BATTERY, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Battery Position
 - Battery Type
 - Battery Serial Number
 - Battery Voltage (V)
 - Battery Remaining (%)

:::

::::

#### CFG_CHANNEL, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Channel
 - Detection Type
 - Frequency (kHz)
 - Blanking (ms)
 - Map ID
 - Coding ID

:::

::::

#### CFG_STATION, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Station Name
 - Latitude (deg)
 - Longitude (deg)

:::

::::

#### CFG_STUDY, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Description

:::

::::

#### CFG_TRANSMITTER, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Transmission Type
 - Full ID
 - ID
 - Power Level
 - Min Delay (s)
 - Max Delay (s)

:::

::::

#### CLOCK_REF, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - External Time (UTC)
 - External Difference (s)
 - Source

:::

::::

#### CLOCK_SET, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - Prior Difference (s)
 - Source

:::

::::

#### DATA_ERROR, n = 5

:::: {style="display: flex;"}

::: {}

 - Type
 - Error
 - Page

:::

::: {}

 - Offset
 - Description

:::

::::

#### DATA_SOURCE_FILE, n = 5

:::: {style="display: flex;"}

::: {}

 - File Name
 - UUID
 - Type

:::

::: {}

 - Size
 - State

:::

::::

#### DEPTH, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Depth (m)

:::

::::

#### DEPTH_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Depth Min (m)
 - Depth Max (m)
 - Depth Mean (m)
 - Sample Count
 - Accumulation Period (s)

:::

::::

#### DET, n = 20

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID

:::

::: {}

 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### DET_FILTER, n = 3

:::: {style="display: flex;"}

::: {}

 - Filter Name
 - Details

:::

::: {}

 - Rejected Detections

:::

::::

#### DET_SENS, n = 25

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID
 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)

:::

::: {}

 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP
 - Transmitter Type
 - Sensor Function
 - Sensor Value
 - Sensor Unit
 - Sensor Precision

:::

::::

#### DIAG, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Temperature (deg C)
 - Noise Mean (mV)
 - Tilt (deg)
 - Depth (m)
 - PPM Pings
 - PPM Detections

:::

::::

#### DIAG_FAST, n = 10

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Ambient Temperature (deg C)
 - Noise (mV)
 - Tilt (deg)
 - Depth (m)

:::

::::

#### DIAG_VR2W, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Pings
 - Detections

:::

::::

#### DIAG_VR2W_INTERIM, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Pings
 - Detections

:::

::::

#### EVENT, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Type

:::

::: {}

 - Subtype
 - Description
 - Values
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### EVENT_FAULT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Fault Importance
 - Fault Code
 - Fault Description

:::

::::

#### EVENT_INIT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - External Time Zone
 - Firmware Version

:::

::::

#### EVENT_OFFLOAD, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - External Time (UTC)

:::

::: {}

 - External Time Zone
 - HR Total Accepted Detections
 - PPM Total Accepted Detections
 - Memory Remaining (%)
 - Battery Remaining (%)
 - Original File

:::

::::

#### HEALTH_VR2W, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Memory Remaining (%)
 - RTC Time

:::

::::

#### PING, n = 15

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Frequency (kHz)

:::

::: {}

 - Blanking (ms)
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### TEMP, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Ambient (deg C)
 - Internal (deg C)

:::

::::

#### TEMP_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Min (deg C)
 - Ambient Max (deg C)
 - Ambient Mean (deg C)
 - Sample Count
 - Accumulation Period (s)

:::

::::

### VR2W180 VRL, n = 27

#### ATTITUDE, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Tilt (deg)

:::

::::

#### BATTERY, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Battery Position
 - Battery Type
 - Battery Serial Number
 - Battery Voltage (V)
 - Battery Remaining (%)

:::

::::

#### CFG_CHANNEL, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Channel
 - Detection Type
 - Frequency (kHz)
 - Blanking (ms)
 - Map ID
 - Coding ID

:::

::::

#### CFG_STATION, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Station Name
 - Latitude (deg)
 - Longitude (deg)

:::

::::

#### CFG_STUDY, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Description

:::

::::

#### CFG_TRANSMITTER, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Transmission Type
 - Full ID
 - ID
 - Power Level
 - Min Delay (s)
 - Max Delay (s)

:::

::::

#### CLOCK_REF, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - External Time (UTC)
 - External Difference (s)
 - Source

:::

::::

#### CLOCK_SET, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - Prior Difference (s)
 - Source

:::

::::

#### DATA_ERROR, n = 5

:::: {style="display: flex;"}

::: {}

 - Type
 - Error
 - Page

:::

::: {}

 - Offset
 - Description

:::

::::

#### DATA_SOURCE_FILE, n = 5

:::: {style="display: flex;"}

::: {}

 - File Name
 - UUID
 - Type

:::

::: {}

 - Size
 - State

:::

::::

#### DEPTH, n = 7

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Depth (m)

:::

::::

#### DEPTH_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Depth Min (m)
 - Depth Max (m)
 - Depth Mean (m)
 - Sample Count
 - Accumulation Period (s)

:::

::::

#### DET, n = 20

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID

:::

::: {}

 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### DET_FILTER, n = 3

:::: {style="display: flex;"}

::: {}

 - Filter Name
 - Details

:::

::: {}

 - Rejected Detections

:::

::::

#### DET_SENS, n = 25

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Detection Type
 - Full ID
 - ID
 - Raw Data
 - Transmitter Serial
 - Signal Strength (dB)

:::

::: {}

 - Noise (dB)
 - Gain (dB)
 - Quality Score
 - Station Name
 - Latitude
 - Longitude
 - GPS HDOP
 - Transmitter Type
 - Sensor Function
 - Sensor Value
 - Sensor Unit
 - Sensor Precision

:::

::::

#### DIAG, n = 12

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Temperature (deg C)
 - Noise Mean (mV)
 - Tilt (deg)
 - Depth (m)
 - PPM Pings
 - PPM Detections

:::

::::

#### DIAG_FAST, n = 10

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Ambient Temperature (deg C)
 - Noise (mV)
 - Tilt (deg)
 - Depth (m)

:::

::::

#### DIAG_VR2W, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Pings
 - Detections

:::

::::

#### DIAG_VR2W_INTERIM, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Pings
 - Detections

:::

::::

#### EVENT, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Type

:::

::: {}

 - Subtype
 - Description
 - Values
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### EVENT_FAULT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Fault Importance
 - Fault Code
 - Fault Description

:::

::::

#### EVENT_INIT, n = 9

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model

:::

::: {}

 - Serial Number
 - Prior Device Time (UTC)
 - External Time Zone
 - Firmware Version

:::

::::

#### EVENT_OFFLOAD, n = 13

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - External Time (UTC)

:::

::: {}

 - External Time Zone
 - HR Total Accepted Detections
 - PPM Total Accepted Detections
 - Memory Remaining (%)
 - Battery Remaining (%)
 - Original File

:::

::::

#### HEALTH_VR2W, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Memory Remaining (%)
 - RTC Time

:::

::::

#### PING, n = 15

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number
 - Channel
 - Frequency (kHz)

:::

::: {}

 - Blanking (ms)
 - Signal Strength (dB)
 - Noise (dB)
 - Gain (dB)
 - Latitude
 - Longitude
 - GPS HDOP

:::

::::

#### TEMP, n = 8

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)

:::

::: {}

 - Model
 - Serial Number
 - Ambient (deg C)
 - Internal (deg C)

:::

::::

#### TEMP_STATS, n = 11

:::: {style="display: flex;"}

::: {}

 - Device Time (UTC)
 - Time
 - Time Offset (h)
 - Time Correction (s)
 - Model
 - Serial Number

:::

::: {}

 - Ambient Min (deg C)
 - Ambient Max (deg C)
 - Ambient Mean (deg C)
 - Sample Count
 - Accumulation Period (s)

:::

::::
